name: Daily Commit Job

on:
  schedule:
    - cron: '30 5 * * *'  # Runs every day at 05:30 UTC

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Make a change with 24f2007248@ds.study.iitm.ac.in
        run: |
          date > daily_commit.txt

      - name: Commit and Push Changes
        run: |
          git config --global user.name "Auto Commit Bot"
          git config --global user.email "24f2007248@ds.study.iitm.ac.in"
          git add daily_commit.txt
          git commit -m "Daily commit at $(date)"
          git push
